version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "06:31"
