sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

before_script:
- rustup component add rustfmt-preview

script:
- cargo test --all
- if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
    cargo fmt -- --check;
  fi
